### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-1-infografia-Arlet04#2]
[Ciclo de Vida de un Sistema.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Arlet04/files/12564560/Ciclo.de.Vida.de.un.Sistema.pdf)

**Comment by JeroRoque** [comment]
calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
